// A interface compartilha os MESMOS tipos do motor — nada é redeclarado.
export type {
  AlertRecord,
  AppSettings,
  AssetView,
  AuditEntry,
  AutoTradeSettings,
  DecisionRecord,
  EquityPoint,
  FactorPerformance,
  GuardSettings,
  BtcContextState,
  Candle,
  ConnectionState,
  DashboardSnapshot,
  MarketContext,
  PerformanceStats,
  RiskSettings,
  ScoreBreakdown,
  ScoreComponent,
  SetupClassification,
  SetupType,
  SetupVisualState,
  Timeframe,
  ScannerSettings,
  SetupEvidence,
  Trade,
  TradeSetup,
  TradingMode,
  UniverseMode,
} from '../../../src/core/types.ts';
